package project.rico.darirumah.config;

import lombok.Getter;
import lombok.Setter;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Configuration;

/**
 * App Properties
 * generated by initializr
 */
@Getter
@Setter
@Configuration
@ConfigurationProperties("app")
public class AppProperties {
    //TODO APP Config
    private String APP_NAME = "darirumah";
    private String APP_VERSION = "V1";

    public static String SCHEMA = "darirumah";

    /*SOLACE SETTING*/
    private String SOLACE_SMS_QUEUE_DESTINATION = "event-darirumah-paid";
    private int ASYNC_CORE_POOL_SIZE = 25;
    private int ASYNC_MAX_POOL_SIZE = 50;
    private int ASYNC_QUEUE_CAPACITY = 25;

}