package project.rico.darirumah.config;

import lombok.Getter;
import lombok.Setter;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Configuration;

import java.util.Map;

/**
 * App Properties
 * generated by initializr
 */
@Getter
@Setter
@Configuration
@ConfigurationProperties("app")
public class AppProperties {
    //TODO APP Config
    private String APP_NAME = "sharequota-mm.service";
    private String APP_VERSION = "V1";


}
